version: "3"

services:
    file-server:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: file-server
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./files:/www/data